[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']

metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # store source code in the json file directly

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
